### ISSUE TITLE
Idea: Make configuration more similar to cosmos:browserify

### ISSUE THREAD

**Issue by stubailo** [Meteor-Community-Packages/meteor-postcss#1]
https://github.com/elidoran/cosmos-browserify#1-enable-app-npm-modules

I think this is a good pattern, and we should just make it a de-facto "standard" way to configure packages that require NPM plugins.

**Comment by juliancwirko** [comment]
I wonder if this will do the same. 
Here I need to call `require('...');` in the minifier file (in the package) for the postCSS's process method. 
I don't want to do it in the app. But maybe it is better to do it in the app if we still be able to use it in the minifier package through globals. Anyway I will try to do it with browserify. I need to play with it a little bit. I haven't used it so much :)

**Comment by stubailo** [comment]
I'm not saying you need to do it through browserify at all.

I'm just saying the way the configuration is described makes sense to me. Instead of asking people to make a local package and then pass the path to the package, why not just recommend using `meteorhacks:npm`, and then use that package path by default?

**Comment by juliancwirko** [comment]
Oh, ok, this is a good idea. I'll try to rewrite it.

**Comment by juliancwirko** [comment]
updated... it uses npm-container and meteorhacks:npm

**Comment by stubailo** [comment]
Looks really awesome! I'd love to check it out soon. I'll add this to the build tool discussion for the guide.

**Comment by juliancwirko** [comment]
Cool! 
What is needed here is: 
- separation of [standard-minifiers](https://github.com/meteor/meteor/tree/devel/packages/standard-minifiers) package (js, css)
- better solution for passing postCSS plugins from outside and also plugin's options. Related https://github.com/meteor/meteor/issues/5512

...but for now it works. I'll try to manually test it in different use cases, also I will try to add some tests

**Comment by stubailo** [comment]
Sounds great!

**Comment by stubailo** [comment]
So standard minifiers has been split: https://github.com/meteor/meteor/pull/5592

(Not that it helps much since that is not released yet)

**Comment by juliancwirko** [comment]
:+1: ok, I'll update the package when there will be a new Meteor version released.

**Comment by stubailo** [comment]
OK my only remaining concern is the configuration issue, hopefully we can get that one in soon as well.
