### ISSUE TITLE
postcss is digging into Meteor packages and yielding errors

### ISSUE THREAD

**Issue by ffxsam** [Meteor-Community-Packages/meteor-postcss#14]
Is there some way to blacklist Meteor packages? It doesn't like what `babrahams:constellation` is doing.

```
   While minifying app stylesheet:
   packages/constellation_console/client/Constellation.css:118:3:
   postcss-simple-vars:
   /Users/samh/tmp/packages/constellation_console/client/Constellation.css:118:3:
   Undefined variable $c1

   Css Syntax Error.

   postcss-simple-vars:
   /Users/samh/tmp/packages/constellation_console/client/Constellation.css:118:3:
   Undefined variable $c1
   background-image: -o-linear-gradient(#000, #000);
   filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='$c1',
   endColorstr='$c2',GradientType=0);
   ^
   color: rgba(255, 255, 255, 0.6);
```

**Comment by juliancwirko** [comment]
Hmmm, this is because of not standard CSS usage here - filter hack for MS. Actually this is a proper behaviour of [postcss-simple-vars](https://github.com/postcss/postcss-simple-vars). But maybe you're right, maybe we should have some kind of packages filter. I'll try to look into it.

**Comment by juliancwirko** [comment]
Ok, I think it should work now. Added `excludedPackages` option. Here are the docs about it: https://github.com/juliancwirko/meteor-postcss#exclude-meteor-packages 

You just need to exclude `constellation:console` package.

**Comment by ffxsam** [comment]
Did you push a new version to Atmosphere? I'm not seeing an updated package.

**Comment by juliancwirko** [comment]
Yes, the new version is 1.1.0 and it is even displayed here: https://atmospherejs.com/juliancwirko/postcss :) so it should work. 

The [demo project](https://github.com/juliancwirko/meteor-postcss-test) uses it already.

**Comment by ffxsam** [comment]
Oops! My mistake. Testing this out now..

**Comment by ffxsam** [comment]
Works like a charm. Thanks for this! :)

**Comment by maddijoyce** [comment]
Hi, is there any way to note an excludedPackages in the non-1.3 version?
Getting this error on an app I haven't had time to update to new meteor.

Thanks,
Maddi

**Comment by juliancwirko** [comment]
@maddijoyce I'm afraid not :/ Updating to Meteor 1.3 shouldn't be very hard. You don't need to use new architecture with imports in Meteor 1.3
