### ISSUE TITLE
How to use css-modules?

### ISSUE THREAD

**Issue by comerc** [Meteor-Community-Packages/meteor-postcss#17]
I need [css-modules](https://github.com/css-modules/css-modules) with sugarss, but [meteor-css-modules](https://github.com/nathantreid/meteor-css-modules) does not support parser-option. :(

**Comment by juliancwirko** [comment]
Yes, you're right. I am sure that @nathantreid can implement it. It would be awesome.
Unfortunatelly this package won't support css-modules.

**Comment by comerc** [comment]
[support of sugarss](https://github.com/nathantreid/meteor-css-modules/pull/38)
