### ISSUE TITLE
Failed to parse SourceMap

### ISSUE THREAD

**Issue by zhaoyao91** [Meteor-Community-Packages/meteor-postcss#19]
there seems some problem, by using this package, browser complain: 

`Failed to parse SourceMap: http://192.168.0.55:3000/8e8a4e9e315940d9ada85534386a140f483d644f.map`
and I can't locate at currect line of code in browser.

I test app with many other package: less-autoprefixer, seba:minifiers-autoprefixer, and standard-minifier-css, there is no such problem.

**Comment by juliancwirko** [comment]
Hi, could you prepare small reproduction repo? Thanks.

**Comment by zhaoyao91** [comment]
It may be the problem of meteor on windows. I have to spent some time to figure it out.
