### ISSUE TITLE
CSS files inside the Imports directory are not being picked up.

### ISSUE THREAD

**Issue by perinikhil** [Meteor-Community-Packages/meteor-postcss#24]
I want to use autoprefixer to prefix my CSS files.

Following the new directory structure from Meteor 1.3, I've defined my components to contain a single HTML, CSS and JS file. The problem is, autoprefixer does not pick up the CSS files defined inside of the Imports root level directory.

**Comment by perinikhil** [comment]
The PostCSS and autoprefixer plugins work fine when the styles are defined in the Client root level directory however.

**Comment by mimamuh** [comment]
Hey, I can't speak for this package, but it's the normal behaviour of meteor to not import stuff from the import folder automatically. You may have to import your css files like described [here](https://guide.meteor.com/build-tool.html#css-importing) from your `import` folder to your `client` folder?

**Comment by juliancwirko** [comment]
For imports you can use stylus or scss package. It works if you need to do something like:

in main.styl
```
@import '{}/imports/ui/stylesheets/test.styl';
```
in imports/ui/stylesheet/test.styl:
```
.test1
  display flex
```

example output:
```
.test1 {
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
}
```

Of course you need to have stylus package installed, autoprefixer from npm, and you need to configure postcss package properly.
