### ISSUE TITLE
PostCSS latest version

### ISSUE THREAD

**Issue by HBCharles** [Meteor-Community-Packages/meteor-postcss#27]
Is it possible to update the latest version of PostCSS ?

I got this message when starting my app : 

`Your current PostCSS version is 5.0.14, but postcss-inline-svg uses 5.2.5.`

**Comment by juliancwirko** [comment]
Hi, yes, I'll try to test it with newest Meteor version and update all dependencies. I'll try to do this very soon.

**Comment by juliancwirko** [comment]
Updated, it seems that this package works much much better with Meteor 1.4.2 than with previous versions.

**Comment by HBCharles** [comment]
Thanks a lot I close the issue.
