### ISSUE TITLE
Import CSS styles from JS modules

### ISSUE THREAD

**Issue by yanickrochon** [Meteor-Community-Packages/meteor-postcss#28]
In Meteor writing

```js
import 'modulename/dist/css/styles.css';
```

Add styles to the page, but how do I import the actual styles?

```js
import styles from 'modulename/dist/css/styles.css';

console.log( styles.foo );
// -> ... the CSS class name for ".foo"
```

At the moment, a `STYLE` DOM node is returned.

**Comment by juliancwirko** [comment]
Hi, I guess you want to use CSS Modules here, right? Meteor's build system doesn't support CSS Modules and this package is not for it too. If you want to use CSS Modules in Meteor you could check the https://atmospherejs.com/nathantreid/css-modules
