### ISSUE TITLE
Error thrown when using this with the latest postcss-nested

### ISSUE THREAD

**Issue by nbiton** [Meteor-Community-Packages/meteor-postcss#30]
```Node#after is deprecated. Use Node#raws.after
Your current PostCSS version is 5.1.2, but postcss-nested uses 6.0.6. Perhaps this is the source of the error below.

/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Processing Step: CSS Modules / PostCSS compilation
Unable to compile /media/naor/OS/Projects/unee-t-fe/imports/ui/claim/claim.css
TypeError: after.after is not a function

/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
=> Errors prevented startup:
   
   While processing files with nathantreid:css-modules (for target web.browser):
   error: after.after is not a function
   
=> Your application has errors. Waiting for file change.
```

This is what shows up when running this with the latest `postcss-nested` plugin.
Downgrading `postcss-nested` to 1.0.1 works around the problem.
I guess other new plugin versions could stop working too due to incompatibility.

**Comment by mhshakouri** [comment]
I think updating the npmDependencies in the root package.json to the proper version or latest version should do it.
`
    npmDependencies: {
        'source-map': '0.5.6',
        'postcss': '5.2.5',
        'app-module-path': '2.1.0'`

there is this postcss fellow here, it's the mismatching version causing you the trouble. 
version handling in npm can sometimes get tricky but I guess just upgrading these guys here, at lease I can be sure you can set the source map and post css version set to be * to get the latest versions.

**Comment by juliancwirko** [comment]
I'll try to update deps when Meteor 1.6.1 will be ready, because there will be some important fixes in minifier-css too

**Comment by juliancwirko** [comment]
Updates done (v1.3)

**Comment by juliancwirko** [comment]
I'll close this one for now. Feel free to comment here if needed.
