### ISSUE TITLE
Different configuration for production and non-production?

### ISSUE THREAD

**Issue by mitar** [Meteor-Community-Packages/meteor-postcss#31]
autoprefixer takes a lot of time. Is there a way to have a different set of plugins during development? So that autoprefixer runs only when bundling?

**Comment by mitar** [comment]
This has been fixed by #32.

Now you can create `.postcssrc.js` file in the root of the app with things like:

```js
module.exports = (ctx) => {
  if (ctx.meteor) {
    const config = {
      plugins: {
        'postcss-easy-import': {},
      },
    };

    if (ctx.env === 'production') {
      // "autoprefixer" is reported to be slow,
      // so we use it only in production.
      config.plugins.autoprefixer = {
        browsers: [
          'last 2 versions',
        ],
      };
    }

    return config;
  }
  else {
    return {};
  }
};
```

**Comment by juliancwirko** [comment]
@mitar I haven't tested all, but is the `postcss` entry in package.json compatible with what was here previously? Or should I rewrite the docs for new 2.0.0 version?

**Comment by mitar** [comment]
Yes, it should just continue to work. There are maybe some internal changes because of now using `require` and not `Npm.require`. This might improve things, but it could also break things if people were doing some workarounds. So I do not think it is a major change, but it is definitely a minor one.

**Comment by mitar** [comment]
Before release, we could also bump the version of PostCSS, and also add some documentation about new locations where you can put configuration. I can do those pull requests if you want.

**Comment by juliancwirko** [comment]
Of course. It would be better if you'll do that. I've released it, but no problem, I'll release it again.
