### ISSUE TITLE
Moving to Community Maintenance 

### ISSUE THREAD

**Issue by copleykj** [Meteor-Community-Packages/meteor-postcss#41]
> Important! Package is no longer actively maintained. I am not sure if it will work with newest Meteor versions. If you think you can keep it in good shape, let me know. I'll pass it to you. Thanks.

Since this isn't being actively maintained any longer, would you be willing to transfer it to the Meteor-Community-Packages org to be maintained by the community? See Meteor-Community-Packages/organization#49 for further discussion.

**Comment by juliancwirko** [comment]
Sure, what should I do to make it happen?

**Comment by copleykj** [comment]
Awesome! Thanks for the quick response. I've sent you an invite to join the org. Once joined you can transfer the repo under the settings tab. When that's done we'll just need you to add `communitypackages` to the maintainers for the package.

```sh
meteor admin maintainers juliancwirko:postcss --add communitypackages`
```

Once those 2 things are done, that should be all that is required of you. You can feel free to stay a member of the Meteor-Community-Packages org if you'd like, or you can also remove yourself.
