### ISSUE TITLE
Can't publish without node_modules present, but node_modules causes empty objects returned from require

### ISSUE THREAD

**Issue by copleykj** [Meteor-Community-Packages/meteor-postcss#43]
So I've updated the peer deps required by the package and everything worked great locally. Upon trying to publish the new version though meteor complained that the `postcss` and `postcss-load-config` modules were missing. I installed them and published successfully. Upon installing it in the app that I tested it in locally, it threw an error that `load` was not a function. Upon investication it seems that that node_modules folder gets published with the package and somehow interferes with the package when installed.

If I symlink the package to the local app again and just remove the node_modules folder, the error is gone and everything works again. @juliancwirko has this been an issue in the past or is this something that's changed in Meteor since the previous version was published?

**Comment by juliancwirko** [comment]
Hi, I stopped work on this package a couple of years ago nor have I worked with Meteor for several years. I'm afraid that I won't be able to help with that. I don't remember such problems, but I remember that there were difficulties related to Meteor architecture in the course of subsequent version updates or lack of proper changes in Meteor.

**Comment by copleykj** [comment]
@juliancwirko Thanks for your time, and the quick reply! I guess I'll have to file and issue in the Meteor repo and see anyone can provide any insights.
