### ISSUE TITLE
Compatibility with Meteor 1.3

### ISSUE THREAD

**Issue by priezz** [Meteor-Community-Packages/meteor-postcss#6]
Hello, what are the plans to make this brilliant package more aligned with Meteor 1.3 capabilities by removing the dependancy from meteorhacks:npm and using new built-in Meteor facilities for npm?

**Comment by juliancwirko** [comment]
Yes, I'll work on it as soon as the 1.3 appears. Also we need to split js and css minifiers because in 1.3 there are separated packages for them. 
If I find some time, I'll create a branch for 1.3 modifications before Meteor 1.3 release.

**Comment by juliancwirko** [comment]
There is a branch for it: https://github.com/juliancwirko/meteor-postcss/tree/meteor-1.3-in-progress , but there will be probably some changes till Meteor 1.3 
We need to wait

**Comment by priezz** [comment]
Thank you for the quick update! Have you pushed the newer version to atmosphere?

```
$ meteor add juliancwirko:postcss@1.0.0
 => Errors while parsing arguments:           

While adding package juliancwirko:postcss@1.0.0:
error: no such version juliancwirko:postcss@1.0.0
```

Without `@1.0.0` it installes version 0.2.5.

I am running Meteor `METEOR@1.3-modules-beta.4 meteor`.

**Comment by juliancwirko** [comment]
No it isn't on Atmosphere. I don't want to push the beta. But you can clone the branch and test it as local package for now, it should work that way too. 
I think there could be some small changes so it is better to not push it right now.

**Comment by priezz** [comment]
I see, thanks!

**Comment by juliancwirko** [comment]
although I can release `1.0.0_beta-1` but it could be confusing and I don't know if many people want to use this package with beta version of Meteor 1.3

**Comment by priezz** [comment]
I believe you can publish 1.0.0_beta, which is dependant on Meteor 1.3 and
up. In this case Meteor 1.2 users will still use 0.2.5. Maybe I am wrong
and Meteor packaging system works differently ☺ In this case that could be
the separate package (:postcss_beta or similar).

**Comment by juliancwirko** [comment]
Yes, you're right. It should work that way. Ok I'll try to find a moment to improve docs (there should be some text about migration from older versions which uses meteorhacs:npm because it isn't automatic, you need to clean npm-container .json files etc.) Anyway I'll try to push the beta to the Atmosphere today.

**Comment by priezz** [comment]
Great!

**Comment by juliancwirko** [comment]
Ok, there is `1.0.0-beta.1` on Atmosphere. You need to remove package and add it by `meteor add juliancwirko:postcss@1.0.0-beta.1`

You can also clean the project. Here is the info:
https://github.com/juliancwirko/meteor-postcss/tree/meteor-1.3-in-progress#migration-from-older-version

**Comment by juliancwirko** [comment]
... also there are changes in "Usage" section: 
https://github.com/juliancwirko/meteor-postcss/tree/meteor-1.3-in-progress#usage

**Comment by priezz** [comment]
Julian, it works like a charm!
