### ISSUE TITLE
Update to use the new `1.3-beta.9` release

### ISSUE THREAD

**Issue by tmeasday** [Meteor-Community-Packages/meteor-postcss#7]
Hey @juliancwirko! 

Thanks so much for this package, it is great.

We are in the process of doing a new beta release `1.3-modules-beta.8 -> 1.3-beta.9`. We renamed the beta as now it includes all the features that'll be in 1.3 (yay!). As a result the dependency system won't let us run the Todos example app with the current beta version of your package.

So this is a simple request to push a new beta version with bumped dependencies! 

Thanks again, let me know if I can help.

**Comment by martijnwalraven** [comment]
Note that we're skipping `1.3-beta.9`, so it'll be `1.3-beta.10`!

**Comment by juliancwirko** [comment]
Hi, ok, in a couple of minutes I'll bump it for `release/METEOR@1.3-beta.10`.

**Comment by martijnwalraven** [comment]
Great! You'll probably receive an error for now though, because we're having some trouble publishing the release.

**Comment by juliancwirko** [comment]
Yeah, I can't update my demo project with `meteor update --release 1.3-beta.10`. (`Sorry, Meteor 1.3-beta.10 is not installed and could not be downloaded.`)

I think that there is a change with `css-minifier` (the name was changed?) so it will be better to test it first on my demo project. 

I'll keep trying to update it.

**Comment by martijnwalraven** [comment]
Sorry for the confusion, I'm trying to fix a problem with our build farm. I'll let you know when I succeed!

**Comment by juliancwirko** [comment]
There is `juliancwirko:postcss@1.0.0-beta.11` (previously it was beta.1)
It seems that everything works well on my demo app.

Altought I had a little problem with update. I needed to remove `standard-minifiers-js` first and then add `standard-minifier-js` before `meteor update --release 1.3-beta.11`. This is because name changes.

**Comment by martijnwalraven** [comment]
Thanks! We had some difficulties with the package server (turned out not to be the build farm), so I couldn't release until a few hours ago.

There have indeed been name changes related to the minifiers.

**Comment by tmeasday** [comment]
Thanks @juliancwirko! Works great on our Todos app
