### ISSUE TITLE
In meteor 1.3 beta, why npm stored in npm devDependencies not in dependencies?

### ISSUE THREAD

**Issue by khaledkbadr** [Meteor-Community-Packages/meteor-postcss#8]
Hello,
I've notices in the package.json sample you provided in the `README`, npm dependencies is stored in using `npm ...--save-dev`, is there a reason for that?. And if I had `NODE_ENV` to be `production` would it fail?

**Comment by juliancwirko** [comment]
Here is a very good explanation: http://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies
... in this particular case this isn't so important, but all that postcss plugins are actually dev dependencies so I think this is the place for them. 

First you need to run `npm install` anyway, so there is no difference if you run Meteor with NODE_ENV in production it will already have all dependencies installed.
